### ISSUE TITLE
Can't input Japanese.

### ISSUE THREAD

**Issue by manzyun** [snapcrafters/atom#20] opened 2017-11-23 06:56 UTC
# Reploduction

1. Install this Snap.
     ``` shell-session
    $ sudo snap install atom --classic
    ```
2. Running this Snap.
    ``` shell-session
    $ snap run atom
    ```
3. Use input Japanese by `ibus-mozc`.

# Matter

I can't input Hiragana, Alphabet instead.

# Ideal

I want use input method engine on this Snap.

However, I think so Snappy not accepts input from input method engine.

# Environment

* OS: Ubuntu 17.10 Artful
* Kernel: x86_64 Linux 4.13.0-17-lowlatency
* Shell: fish 2.6.0
* Desktop environment: Gnome Shell(Ubuntu default)
* CPU: Intel Core i5 M 450 @ 4x 2.4GHz
* RAM: 7650MiB

# P.S.

I'm bat English too, but please forgive me.

**Comment by manzyun** [comment] 2017-12-02 00:15
I'm notice running log today.

```
WARNING: icon cache generation failed for /home/manzyun/snap/atom/76/.local/share/icons/ubuntu-mono-light
Cannot load module /usr/lib/x86_64-linux-gnu/gtk-2.0/2.10.0/immodules/im-ibus.so: GModule (/usr/lib/x86_64-linux-gnu/gtk-2.0/2.10.0/immodules/im-ibus.so) initialization check failed: GLib version too old (micro mismatch)
/usr/lib/x86_64-linux-gnu/gtk-2.0/2.10.0/immodules/im-ibus.so does not export GTK+ IM module API: GModule (/usr/lib/x86_64-linux-gnu/gtk-2.0/2.10.0/immodules/im-ibus.so) initialization check failed: GLib version too old (micro mismatch)
Cannot load module /usr/lib/x86_64-linux-gnu/gtk-2.0/2.10.0/immodules/im-fcitx.so: GModule (/usr/lib/x86_64-linux-gnu/gtk-2.0/2.10.0/immodules/im-fcitx.so) initialization check failed: GLib version too old (micro mismatch)
/usr/lib/x86_64-linux-gnu/gtk-2.0/2.10.0/immodules/im-fcitx.so does not export GTK+ IM module API: GModule (/usr/lib/x86_64-linux-gnu/gtk-2.0/2.10.0/immodules/im-fcitx.so) initialization check failed: GLib version too old (micro mismatch)
```

I see...

**Comment by flexiondotorg** [comment] 2017-12-19 18:12
@manzyun Please can you test this again using the Atom 1.23.1 snap from stable.

**Comment by manzyun** [comment] 2017-12-26 12:01
@flexiondotorg Thank you reply to me.

I have good result and but result.

## Bad Result

I can not input Hiragana this time too.

## Good Result

https://github.com/snapcrafters/atom/issues/20#issuecomment-348648647 log is not displayed. :+1:

----

Well... I though Atom plug-in might be a cause. I use [vim-mode-plus](https://atom.io/packages/vim-mode-plus).

I will cooperate with the survey as much as possible :muscle: 

First I will try running Atom disable plug-ins.

**Comment by flexiondotorg** [comment] 2018-01-05 16:32
@manzyun Atom 1.23.2 is released to the stable channel. Did you confirm that a plugin was at fault?

**Comment by manzyun** [comment] 2018-01-07 12:38
@flexiondotorg Thank you tell me about Atom 1.23.2 is released. but, nothing changed.

> Did you confirm that a plugin was at fault?

No. Nothing special.

----

By the way. I haven't tried another apps about Input Japanese.
I examine it as a personal matter.

**Comment by flexiondotorg** [comment] 2018-01-10 14:54
Sorry, I don't understand your feedback. Is this still an issue?

**Comment by manzyun** [comment] 2018-01-11 01:57
> Is this still an issue?

Yes. This issue is not resolved.
Sorry, me too.

**Comment by extraymond** [comment] 2018-03-30 14:01
+1 for the problem.

Here's my setup:

1. Distro: ubuntu 16.04 64bit
2. Atom:  Snap version 145
3. Input methd: ibus, fcitx


However, this only started to show up after version 136.
With version prior to 136(included), ibus or fcitx both works on my setup. 
But after recent update to 141, I'm unable to type with CJK input methods.

Hope this info can help bisecting the problem.

**Comment by extraymond** [comment] 2018-03-30 14:09
Update:

The latest version without this problem is version 138.
It started to not let ibus show up after this version.

**Comment by extraymond** [comment] 2018-04-11 22:50
Any updates on this?

**Comment by extraymond** [comment] 2018-04-22 01:02
Since moved to another machine... there were no version 138 installed on that machine before, so I can't  revert back to that revision.

When trying to refresh to specific version with --revision flag:

```bash
snap refresh atom --revision=137
```

It says that it's not permitted to access revision for this atom:

```bash
error: cannot refresh "atom": Access by specifying a revision is not allowed for this Snap.
```

I think this affects most new installs as well.
I can confirm this is not happening on official atom deb.

Since it all started happening after 138,  which is after commit dddbecb, I believe this is something related to how atom utilize libgconf.

Hope someone with more experience can help me bisect this bug.

**Comment by manzyun** [comment] 2018-05-26 04:21
Hello. I haven't seen you for a long time. Sorry...

By the way, I think this forum topic is relation this issue.
[Can't use input method in snap apps - snapd - snapcraft.io](https://forum.snapcraft.io/t/cant-use-input-method-in-snap-apps/4712)

However, I'm not get a definite idea to fitly action.
May I tell forum thread about this issue?

**Comment by extraymond** [comment] 2018-07-02 20:19
It would be nice if someone in the forum who knows more can help us. I really like the auto update feature from atom snap.

**Comment by extraymond** [comment] 2018-09-06 04:32
Is there any updates in this?
I use atom as a text editor for slides and draft too. It would be nice to have input method support back.

**Comment by manzyun** [comment] 2018-09-08 06:47
Sorry to keep you waiting.
I upgraded Atom to version 1.30.0 and tried to make Japanese input possible.

But, nothing has changed.

By the way,
When Atom started up, there was such a record in Atom's log.
For your reference.

```
 spell-check:ja The package `spell-check` cannot load the system dictionary for `ja`. See the settings for ways of changing the languages used,  resolving missing dictionaries, or hiding this warning.

The plugin checked the following paths for dictionary files:
* /usr/share/hunspell
* /usr/share/myspell
* /usr/share/myspell/dicts
* /snap/atom/192/usr/share/atom/resources/app.asar.unpacked/node_modules/spellchecker/vendor/hunspell_dictionaries
```

**Comment by extraymond** [comment] 2018-09-08 06:55
@manzyun  No biggie!

I think the problem is rooted for the change after the last working version (135) .

Looking at the diff log, I think [this commit](https://github.com/snapcrafters/atom/commit/dddbecb94f9e0cf7283c88521495ef148cfbeddb) might be the reason.

This is the commit that made into 136.

**Comment by manzyun** [comment] 2018-09-16 05:32
Well... I would like you to tell me if I made a mistake.

I read [Pre-built apps - Snaps are universal Linux packages](https://docs.snapcraft.io/build-snaps/pre-built) and build this repository.

However, when `snapcraft` was executed, an error was output.
This log:
```
$ snapcraft 
DEPRECATED: The 'prepare' keyword has been replaced by 'override-build'
See http://snapcraft.io/docs/deprecation-notices/dn7 for more information.
DEPRECATED: The 'install' keyword has been replaced by 'override-build'
See http://snapcraft.io/docs/deprecation-notices/dn9 for more information.
DEPRECATED: The 'prepare' keyword has been replaced by 'override-build'
See http://snapcraft.io/docs/deprecation-notices/dn7 for more information.
Skipping pull atom (already ran)
Skipping pull launcher (already ran)
Skipping build atom (already ran)
Skipping build launcher (already ran)
Skipping stage atom (already ran)
Skipping stage launcher (already ran)
Priming atom 
The linker version '2.23' used by the base 'core' is incompatible with files in this snap:
    /home/manzyun/Projects/atom/prime/lib/x86_64-linux-gnu/libbsd.so.0.8.7 (2.25)
    /home/manzyun/Projects/atom/prime/lib/x86_64-linux-gnu/libexpat.so.1.6.7 (2.25)
    /home/manzyun/Projects/atom/prime/usr/lib/x86_64-linux-gnu/libexpatw.so.1.6.7 (2.25)
    /home/manzyun/Projects/atom/prime/usr/lib/x86_64-linux-gnu/libgnutls.so.30.14.10 (2.25)
    /home/manzyun/Projects/atom/prime/usr/lib/x86_64-linux-gnu/libp11-kit.so.0.3.0 (2.26)
    /home/manzyun/Projects/atom/prime/usr/lib/x86_64-linux-gnu/libxshmfence.so.1.0.0 (2.27)
    /home/manzyun/Projects/atom/prime/usr/lib/x86_64-linux-gnu/pulseaudio/libpulsecommon-11.1.so (2.27)
```

**Comment by extraymond** [comment] 2018-09-16 05:45
@manzyun  Are you trying to create a new atom snapcraft.yaml file? Can you share the repo? I would like to learn building snaps too.

**Comment by manzyun** [comment] 2018-09-21 06:19
@extraymond 
I'm not make repository... 🙇 
After cloning this repository, I built it as it was.

**Comment by lostncg** [comment] 2018-11-20 16:16
Im facing the similar issue, but it is Chinese input method based on iBus
The issue still exists on latest snap released.
I believe here is a post which could help you to fix this issue
https://forum.snapcraft.io/t/failed-to-input-chinese-in-many-snap-apps/7251

**Comment by flexiondotorg** [comment] 2019-02-19 15:01
Fixed via #47

**Closed as completed by flexiondotorg** 2019-02-19 15:01 UTC

**Comment by extraymond** [comment] 2019-02-19 15:06
Thx!!!

**Comment by ghost** [comment] 2019-10-12 04:29
Hi, this issue is closed in Feb 2019, but I am facing this issue now. IBus does not work in snap Atom(but work fine with snap Chromium).

**My Environment:**
- Ubuntu 19.10 beta
- Atom 1.40.1 x64 from snap
- IBus 1.5.21
- GNOME 3.34.1
- zsh 5.7.1

This issue was fixed by adding GNOME 3.26 backport PPA and now I am using GNOME 3.34.1. Is this the reason of this issue? Should I wait for ubuntu desktop team to start a pull such as "add GNOME 3.34 PPA"?

**Comment by extraymond** [comment] 2020-06-30 07:29
The same problem occurred after upgrading to 20.04, does anyone bump into this too?

@flexiondotorg  Are there any changes to the desktop-helper snap used that causes this? This problem happened for both codium and atom which are all electron based.

**Comment by manzyun** [comment] 2020-07-15 08:25
Hello again.

> The same problem occurred after upgrading to 20.04, does anyone bump into this too?

I received a notice about this Issue and I confirmed it too.
And I encountered the same issue.

I don't know if this will help you, but I've attached a GIF animation I recorded in Peek.
![Recording by Peek at 2020-07-15 17-13](https://user-images.githubusercontent.com/461212/87521403-4e201500-c6bf-11ea-816e-13bafd7d7774.gif)

<details>
<summary>My environment</summary>

* OS: Ubuntu 20.04 LTS
* GNOME Version: 3.36.3
* Window System: Wayland
* RAM: 31.3 GiB
* CPU: AMD® Fx-8320e eight-core processor × 8
* AMD® Pitcairn / AMD® Pitcairn

</details>

**Comment by valerauko** [comment] 2020-11-29 06:42
I can also confirm this is still happening in snap installed atom. Japanese input (mozc) works just fine if installed through the .deb

```
❯ cat /usr/share/gnome/gnome-version.xml
<?xml version="1.0"?>
<gnome-version>
 <platform>3</platform>
 <minor>38</minor>
 <micro>1</micro>
 <distributor>Ubuntu</distributor>
 <!--<date></date>-->
</gnome-version>
```
```
❯ snap version
snap    2.47.1+20.10.1
snapd   2.47.1+20.10.1
series  16
ubuntu  20.10
kernel  5.8.0-29-generic
```
```
❯ printf 'Desktop: %s\nSession: %s\n' "$XDG_CURRENT_DESKTOP" "$GDMSESSION"
Desktop: GNOME
Session: gnome
```

I run into this every distro upgrade (so every half year) when the installed debs are removed and I try installing from snap instead.
