### ISSUE TITLE
Unable to fetch

### ISSUE THREAD

**Issue by KristijanZic** [snapcrafters/atom#40] opened 2018-10-24 21:34 UTC
**neofetch:**
OS: Ubuntu 18.10 x86_64 
Kernel: 4.19.0-041900-generic 
Uptime: 24 mins 
Packages: 2740 (dpkg), 50 (flatpak),
Shell: bash 4.4.19 
Resolution: 1920x1200, 1680x1050 
DE: GNOME 3.30.1 
WM: GNOME Shell 
WM Theme: Adwaita 
Theme: Adwaita-dark [GTK2/3] 
Icons: Yaru [GTK2/3] 
Terminal: gnome-terminal 
CPU: Intel i5-2400 (4) @ 3.400GHz 
GPU: AMD ATI Radeon RX Vega 64 
Memory: 2874MiB / 3925MiB 

**When I start Atom, I get this error message and it fails to fetch updates for the extensions etc:**
/snap/atom/204/usr/share/atom/resources/app.asar.unpacked/node_modules/dugite/git/libexec/git-core/git-remote-https: /usr/lib/x86_64-linux-gnu/libcurl.so.4: version `CURL_OPENSSL_3' not found (required by /snap/atom/204/usr/share/atom/resources/app.asar.unpacked/node_modules/dugite/git/libexec/git-core/git-remote-https)
/snap/atom/204/usr/share/atom/resources/app.asar.unpacked/node_modules/dugite/git/libexec/git-core/git-remote-https: /snap/core/current/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1)
/snap/atom/204/usr/share/atom/resources/app.asar.unpacked/node_modules/dugite/git/libexec/git-core/git-remote-https: /snap/core/current/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.27' not found (required by /usr/lib/x86_64-linux-gnu/libgssapi_krb5.so.2)
/snap/atom/204/usr/share/atom/resources/app.asar.unpacked/node_modules/dugite/git/libexec/git-core/git-remote-https: /snap/core/current/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /usr/lib/x86_64-linux-gnu/libgnutls.so.30)
/snap/atom/204/usr/share/atom/resources/app.asar.unpacked/node_modules/dugite/git/libexec/git-core/git-remote-https: /snap/core/current/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.26' not found (required by /usr/lib/x86_64-linux-gnu/libp11-kit.so.0)

**Comment by popey** [comment] 2018-10-25 09:24
Thanks for reporting the issue. What extensions do you have installed, so I can try and reproduce it here? I have installed Atom on 18.10 and installed a couple of packages.

**Comment by lucyllewy** [comment] 2018-10-25 09:37
This looks decidedly like a classic confinement cross-pollination of libraries between the host and the snap

**Comment by daviwil** [comment] 2018-10-25 18:30
This is caused by an issue with [dugite](https://github.com/desktop/dugite) where it doesn't work on machines with `libcurl4` installed.  Thankfully this issue was [fixed recently](https://github.com/desktop/dugite-native/pull/129).  We're going to get it released in an Atom hotfix soon so once the Snap distribution catches up with that this problem should be resolved for you.

**Comment by popey** [comment] 2018-11-12 10:58
Atom 1.32.2 is now in the stable channel, as such this should be fixed now.

**Closed as completed by popey** 2018-11-12 10:58 UTC
