### ISSUE TITLE
Not starting.

### ISSUE THREAD

**Issue by rafifos** [snapcrafters/atom#30] opened 2018-01-22 18:51 UTC
Hi, after installing it on bionic, it doesn't start (neither atom or apm).

Running apm --version from the snap directory (/snap/atom/current/usr/share/atom) returns the desired output. However, running atom from /snap/bin/atom returns this:

`atom: error while loading shared libraries: libgconf-2.so.4: cannot open shared object file: No such file or directory`

I know that this is probably caused by the way snap deals with libraries, and I probably shouldn't try to run atom from this directory, and run it via wrapper, but the bundled wrapper doesn't return anything, neither for atom or for apm).

Thanks in advance, regards.

**Comment by luk71** [comment] 2018-01-31 21:43
Hi,
I've had the same issue on Ubuntu 17.10 (artful).
I resolved by installing libgconf-2-4 package:
apt install libgconf-2-4

Best regards,
Luca

**Comment by DraconPern** [comment] 2018-02-22 06:43
Just installed this on 16.04.  It doesn't run.  Only opens a terminal window then closes. Please fix or remove it from 'ubuntu software'.  It's definitely not stable or usable.

**Comment by martinhamel** [comment] 2018-03-17 00:10
I installed it on ubuntu 16.04 and 18.04beta. It it not available either at the command line or through gnome on either.

**Comment by Ads20000** [comment] 2018-03-21 13:57
Can anyone reproduce what @luk71 reported? If so, could @flexiondotorg include libgconf-2-4 in `stage-packages`? Would that fix the problem?

**Comment by Ads20000** [comment] 2018-03-21 13:58
With libgconf-2-4 installed, I can't reproduce what @DraconPern and @martinhamel reported. You two, can you still not launch with that installed? Needs fixing regardless but this is a different bug if it's not starting even with that package installed (please also give the output of `snap version` and the `tracking` and `installed` lines of `snap info atom` and `snap info core`).

**Comment by JonnyB247** [comment] 2018-03-21 21:24
I had the same problem as @luk71, and the solution worked for me too.

**Comment by martinhamel** [comment] 2018-03-21 23:14
@Ads20000 
Thanks Ads,

I found two problems. I have shell fish installed and it looks like it's breaking the install. Another problem seemed to be related to using wayland. By changing my shell and going back to xorg, everything is working fine. 

But I have to say that it is all too fragile to my tast and that I removed the snap and installed the deb. 

Thanks for the help

**Comment by Ads20000** [comment] 2018-03-21 23:57
> I have shell fish installed and it looks like it's breaking the install. Another problem seemed to be related to using wayland.

Specific Issues filed for those would be good if you had the time! :)

**Comment by devinshoemaker** [comment] 2018-03-22 11:34
I'm also having issues with Atom. If I try and run from my application launcher or from the terminal then my desktop environment immediately crashes and returns to the display manager log in. I have libgconf-2-4 already installed so that did not fix my problem. I am running Kubuntu 17.10 with KDE Plasma and also tried this on the GNOME desktop with the same results. 

EDIT
For what it's worth, the edge build seems to be working while the beta and stable have the same results as I described above.

I also don't have issues on a VM of the same distro and set up, and I tried reinstalling Kubuntu today and Atom still crashes on the stable channel.

**Comment by luk71** [comment] 2018-03-22 19:28
Update:
libgconf-2-4 is needed only with Wayland, with Xorg Atom starts also without it, as reported by @martinhamel

$ snap --version
snap    2.31.2
snapd   2.31.2
series  16
ubuntu  17.10
kernel  4.13.0-37-generic
$ snap list atom
Name  Version  Rev  Developer     Notes
atom  1.25.0   136  snapcrafters  classic

**Comment by bjornramberg** [comment] 2018-03-24 09:50
Recently installed 18.04 Beta 1. Atom from snap installation:
~$ snap  list atom
Name  Version  Rev  Tracking  Developer     Notes
atom  1.25.0   136  stable    snapcrafters  classic

Did not start until the libgconf-2-4  was installed.

**Comment by fcharras** [comment] 2018-03-24 22:46
Reporting same issue, started only after installing libgconf-2-4 .

**Comment by popey** [comment] 2018-03-24 23:25
Once it finishes building, can you try the latest build in the edge channel and see if that fixes it? `snap refresh atom --edge`. Run that and then wait for the update to come down. `snap info` will (in an hour or so) report a new revision in `edge` with the same version number. Let me know if that fixes it.

**Comment by ahmafi** [comment] 2018-09-09 16:22
Same issue with all snap --classic packages.

snap    2.35
ubuntu  18.04
kernel  4.15.0-33-generic

Also, it may be a problem from zsh, /snap/bin removed from PATH. But I run with "snap run" and Wayland crashes.

**Closed as completed** 2019-02-19 16:24 UTC
