### ISSUE TITLE
Slow update cycle

### ISSUE THREAD

**Issue by Bohne13** [snapcrafters/atom#15] opened 2017-10-10 11:52 UTC
Is it possible to speed up the snap release cycle. Atom is actually stable at 1.21.0 but the stable snap is stuck on 1.20.0!

**Comment by Ads20000** [comment] 2017-10-11 19:37
Edit: _the below isn't actually relevant to this specific update_. I might convert this into a forum post for others to use :)

---

To speed it up properly we need the Atom developers themselves to hook the snap into their CI. Then you'd get the snap updated as soon as the new version of Atom is released. The `README.md` for this repo indicates that @flexiondotorg sent an email to the Atom devs with the `snapcraft.yaml` in it, so I guess that means that we've already asked that they integrate into their CI?

If you've got time to help (maybe you haven't, which is fair!) you could help us speed up the release process. When there's an Atom release and you can see by checking the PRs and using `snap info atom` that the update is not on it's way: clone the repo, update the version numbers in the `snapcraft.yaml`, run `snapcraft`, then `sudo snap install atom*.snap --dangerous` (`--dangerous` means it's an unsigned snap because you've built it locally), then `snap run atom`. Test it. If it works OK then make a PR with your version update to the repo and say you've tested it, it works, ask for it to be pushed to the `stable` channel.

Then the snap will be updated for you and everyone who uses the snap!

I'm not an Atom user so if I made a PR it wouldn't be properly tested and would require testing to be pushed to `stable`...unless you think I could safely assume Atom works if I start it up and it works OK?

Instead of running `snapcraft`, you could get a more consistent experience across different Linux distros by running:
```
sudo snap install lxd
sudo lxd init
# just use the default settings when asked (well, I find this easiest, anyway)
sudo lxc launch ubuntu:16.04 snapcraft-builds
SNAPCRAFT_CONTAINER_BUILDS=1 snapcraft
```
After running the above commands once, you should just be able to use `SNAPCRAFT_CONTAINER_BUILDS=1 snapcraft` to build using LXD in the future (maybe you'd need `sudo lxc start snapcraft-builds` first).

**Comment by Ads20000** [comment] 2017-10-11 20:10
Actually, just looked at `snap info atom` myself lol, it's in `edge`, it just needs to be promoted to `stable`.
Can you please confirm that the `edge` snap works (use `sudo snap refresh atom --edge`)? :)

**Comment by Ads20000** [comment] 2017-10-11 20:23
Made a post [here](https://forum.snapcraft.io/t/snapcrafters-github-repo-release-process/2441) on improving the release process.

**Comment by ghisvail** [comment] 2017-10-14 09:23
There is a long running request to provide a better update mechanism which is officially endorsed by the Atom team, see https://github.com/atom/atom/issues/2956.

For instance, Atom stable is now at version 1.21.1, but I really don't feel like asking @flexiondotorg to manually update the snap package every time there is a new release. Considering the quick release cadence of upstream Atom, this solution just does not scale.

Perhaps Martin knows of an on-going initiative upstream to integrate the generation of snap packages within the release process. I heard this is happening for `vscode` and that `electron` was involved in the recent Ubuntu rally. What about Atom, I wonder.

**Comment by popey** [comment] 2017-10-14 10:50
Surely anyone can do a PR for the version number strings in this repo to bump it in the store? We (myself, @evandandrea and @flexiondotorg ) can review and accept that PR, and test the snap before promoting to beta/stable channels. I don't think revving to a new version of Atom (or indeed any application in the snapcrafters area) should depend on one of us editing the version number. That's kinda the point of them being here on github :)

**Comment by Ads20000** [comment] 2017-10-14 12:07
Oh right, so you don't mind people just PR'ing the new version number and URL and leaving it to you three to test?

**Comment by popey** [comment] 2017-10-14 15:11
Ideally I'd like to see people create a PR for the new release. One of us spots that and we approve the PR. When it lands, build.snapcraft.io builds it and pushes to edge. Anyone can then test it, that's the nature of edge.

**Comment by ghisvail** [comment] 2017-10-14 17:37
I don't quite understand how the different channels work. Say Atom wants to provide snaps for their beta releases (currently 1.22betaN), in which channels would these go in then?

**Comment by Ads20000** [comment] 2017-10-15 09:36
`beta`. We won't do beta releases as the snapcrafters repo members (see @evandandrea 's comment [here](https://github.com/snapcrafters/offlineimap/issues/1#issuecomment-328801059) for why), but to explain how this could work if GitHub want to do Atom snaps themselves: when a beta comes out, they can push to `beta` (or `edge` then `beta`). If they want to test a new stable snap, then what they could do is push that to `beta`, get it tested ASAP, then push to `candidate` or `stable` and re-push the actual beta to `beta`. [This is what the `snapd` team did with the `core` snap](https://forum.snapcraft.io/t/2-28-release-cycle-started/2026/6?u=ads20000).

**Comment by ghisvail** [comment] 2017-10-16 13:26
@Ads20000 Thanks for explaining the workflow.

ATM, Atom is at version 1.21 on `edge` and at 1.20 elsewhere. What's the process to get the latest version on `stable` then? Does it need to be pushed manually by a member of `snapcrafters`, or is there some sort of automatic progressive transition from `edge` to `stable` ala Debian testing?

**Comment by Ads20000** [comment] 2017-10-16 14:36
Has to be pushed manually from `edge` to `stable` (or other channels before `stable`) by a snapcrafters Owner (Wimpress, Popey, or Dandrea). I don't have access to do that I'm afraid. If you're able to login to a forum account do like my post [here](https://forum.snapcraft.io/t/snapcrafters-github-repo-release-process/2441) calling for a more formal update process.

If you'd like Atom 1.21 to be more quickly pushed to `stable` then please test the `edge` snap (with `sudo snap refresh atom --edge`, you can use `sudo snap refresh atom --stable` to go back to `stable` once you're done) and tell us how well it works! :) We'll need testing for every release, we don't want to be pushing stuff to `stable` that doesn't work (though if there's no dependency changes it _should_ just work...)

**Comment by ghisvail** [comment] 2017-10-16 14:48
I have been using Atom in `edge` for a week now and it works fine.

The only issue I found is when clicking on a hyperlink (for instance a change log from an Atom package), the latter fails to load and a Firefox crash window pops up instead. It could be related to snaps, since this behavior does not happen with the .deb version.

**Comment by Ads20000** [comment] 2017-10-16 17:28
I can't reproduce your bug when clicking on a link on the Welcome page (e.g. discuss.atom.io)
```
$ snap list
atom                  1.21.0              46    snapcrafters  classic
core                  16-2.28.1           3017  canonical     core
$ snap version
snap    2.28.1
snapd   2.28.1
series  16
ubuntu  17.04
kernel  4.10.0-37-generic
```
Also tried Atom 1.20 (in `stable`) and `core` 16-2.28.5 revision 3212 (in `beta`) with Atom 1.21. I'm on Firefox 56.

Can you give the output of the commands above (just need the `atom` and `core` lines of `snap list`)?

**Comment by ghisvail** [comment] 2017-10-16 17:30
```
$ snap list
Name                Version     Rev   Developer     Notes
atom                1.21.0      46    snapcrafters  classic
core                16-2.28.1   3017  canonical     core
```
```
$ snap version
snap    2.28.5+17.10
snapd   2.28.5+17.10
series  16
ubuntu  17.10
kernel  4.13.0-15-generic
```

**Comment by Ads20000** [comment] 2017-10-16 17:39
Does `sudo snap refresh core --beta` (core 16-2.28.5) fix the issue (you can roll it back afterwards with `sudo snap refresh core --stable` so you don't end up installing `beta`s inadvertently in the future)? See [here](https://forum.snapcraft.io/t/snapd-2-28-xdg-open-doesnt-work-for-electron-applications/2447/).

**Comment by Ads20000** [comment] 2017-10-16 17:41
Wait hold on, your `core` is a different version to your `snapd`...how does that work!?

**Comment by ghisvail** [comment] 2017-10-16 17:43
After your suggestion:
```
$ snap list
atom                1.21.0      46    snapcrafters  classic
core                16-2.28.5   3212  canonical     core
```
And I still get 3 Mozilla crash reports when clicking on a URI

**Comment by ghisvail** [comment] 2017-10-16 17:45
FYI:
```
$ snap info core
name:      core
summary:   snapd runtime environment
publisher: canonical
contact:   snappy-canonical-storeaccount@canonical.com
description: |
  The core runtime environment for snapd
type:        core
snap-id:     99T7MUlRhtI3U0QFgl5mXXESAiSwt776
tracking:    beta
installed:   16-2.28.5 (3212) 87MB core
refreshed:   2017-10-13 23:07:44 +0100 BST
channels:                     
  stable:    16-2.28.1 (3017) 87MB -
  candidate: 16-2.28.1 (3017) 87MB -
  beta:      16-2.28.5 (3212) 87MB -
  edge:      16-2.28.5 (3230) 87MB -
```

**Comment by Ads20000** [comment] 2017-10-16 17:46
Potentially another bug - you've just refreshed your core but `refreshed` says you haven't (maybe your time is out of sync?)...

Edit: I have the same problem. Created forum thread [here](https://forum.snapcraft.io/t/refreshed-timestamp-isnt-accurate/2491).

**Comment by ghisvail** [comment] 2017-10-16 17:50
> maybe your time is out of sync?
```
$ date
Mon 16 Oct 18:49:25 BST 2017
```
Same as on my clock applet.

**Comment by Ads20000** [comment] 2017-10-16 17:54
OK, I've filed a forum thread and hopefully that'll be fixed.
What Terminal output do you get if you use `snap run atom` and then click on a link in Atom (pointing out what Terminal output you get after clicking on the link, rather than just the output you get anyway)?

**Comment by ghisvail** [comment] 2017-10-16 18:02
```
$ snap run atom
ln: failed to create symbolic link '/home/ghislain/snap/atom/46/.config/gtk-2.0/gtkfilechooser.ini': File exists
/usr/share/themes/Ambiance/gtk-2.0/apps/mate-panel.rc:30: error: invalid string constant "murrine-scrollbar", expected valid string constant
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
```

**Comment by Ads20000** [comment] 2017-10-16 18:11
I'm not a programmer (i.e. I probably don't have the experience to _fix_ this issue) but just trying to ask a few more questions so I can diagnose this and open a forum thread on it for others to look at it...

Do you get this bug on Atom 1.20 too (`sudo snap refresh atom --stable`), and do you get this bug when opening links from another snap (e.g. LibreOffice)?

**Comment by ghisvail** [comment] 2017-10-16 18:18
>  do you get this bug when opening links from another snap (e.g. LibreOffice)?

Links from Gitter and RocketChat work fine.

**Comment by ghisvail** [comment] 2017-10-16 18:19
> Do you get this bug on Atom 1.20 too

Yes, same outcome (3 Mozilla crash reports)

**Comment by Ads20000** [comment] 2017-10-16 18:19
Hmm so that implies it may not be a generic problem with snappy, perhaps just the way we've snapped up Atom... @flexiondotorg do you have any ideas at this point? :)

**Comment by Ads20000** [comment] 2017-10-16 18:21
>> Do you get this bug on Atom 1.20 too
> 
> Yes, same outcome (3 Mozilla crash reports)

Ah so this isn't a regression then, that's good.
@flexiondotorg we've had a week's worth of manual testing from a user, is that enough to justify a push Atom 1.21 to `stable` or what more needs to happen for that to happen? :)

**Comment by ghisvail** [comment] 2017-10-16 18:24
> a week's worth of manual testing from a user

And I'll keep using it. I just encountered that bug when trying to read a change log from an Atom package. It is not that much of a deal breaker to me, but it would still be worth fixing I believe.

**Comment by Ads20000** [comment] 2017-10-19 16:05
Could you comment [here](https://forum.snapcraft.io/t/call-for-testing-atom-1-21-1/2533) with the bugs you've encountered (check that this still applies to Atom 1.21.1)? :)

**Comment by ghisvail** [comment] 2017-11-09 11:29
Atom 1.22 is out. Could someone bump the snap please?

**Comment by popey** [comment] 2017-11-09 11:30
building now.

**Comment by ghisvail** [comment] 2017-11-09 11:41
Awesome, thanks Alan.

Any news about the Mozilla crashes when opening URIs in the snapped versions of Atom / VSCode?

**Comment by popey** [comment] 2017-11-10 17:14
I'm closing this issue for now, for other issues, please add them separately. PRs to bump version numbers in yamls are most welcome! :D

**Closed as completed by popey** 2017-11-10 17:14 UTC
