### ISSUE TITLE
Atom snap not findable in Ubuntu 17.10

### ISSUE THREAD

**Issue by ramonsuarez** [snapcrafters/atom#17] opened 2017-10-27 12:36 UTC
I updated my machine yesterday to Ubuntu 17.10 and suddenly I can no longer use the launcher to start Atom. It was installed as a snap and can be launched via the software app (proof that it is installed) but it will not show up when doing a search. I cannot set it as a favorite either.

The version of my Atom snap is 1.21.1 (updated 10/19/2017).  

```
$ snap --version     
snap    2.28.5+17.10     
snapd   2.28.5+17.10     
series  16    
ubuntu  17.10     
kernel  4.13.0-16-generic 
```
There's a [thread about this kind of bug](https://github.com/snapcore/snapd/pull/3398) on snapcore but I can't find/understand a solution there.

**Comment by Ads20000** [comment] 2017-10-27 14:51
I can't reproduce this bug.
```
$ snap version
snap    2.28.5+17.10
snapd   2.28.5+17.10
series  16
ubuntu  17.10
kernel  4.13.0-16-generic
$ snap list
atom                  1.21.1              50    snapcrafters   classic
core                  16-2.28.5           3247  canonical      core
```

**Comment by ramonsuarez** [comment] 2017-10-27 17:06
It does show in the snap list but not in the gui search:
`$ snap list`
`Name  Version    Rev   Developer     Notes`
`atom  1.21.1     50    snapcrafters  classic`
`core  16-2.28.5  3247  canonical     core`

Uninstalling and reinstalling did not solve it. 

Can it be launchend via command line? Just writing Atom does not work.

**Comment by Ads20000** [comment] 2017-10-27 17:46
I was just giving my software versions :P I can see the Atom snap in the GNOME Activities/Applications view (I can also see it in the Unity Dash)
`which atom` will tell you where your `atom` command is launching from. To launch the snap, specifically, use `snap run atom`

**Comment by ramonsuarez** [comment] 2017-10-27 18:24
@Ads20000 thanks for the info. Which did not return anything. Maybe the path got lost in the updates (I went from 16.04 to 17.04 then to 17.10). I've now installed the .deb to work.

**Comment by popey** [comment] 2017-11-10 17:10
I'll close this for now, if anyone else sees this again, please report a new issue. Thanks!

**Closed as completed by popey** 2017-11-10 17:10 UTC
